management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8000
  tomcat:
    threads:
      max: 500

# 配置rocketmq
rocketmq:
  # 指定namesrv地址
  name-server: 121.36.1.4:9876
  producer:
    #生产者group名称
    group: producer_group
    #一次发送多少数量消息
    max-message-size: 4096
    #发送消息超时时间,默认3000
    send-message-timeout: 3000
    #发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 2

spring:
  application:
    name: other-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: dbuser
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      validation-query: select 1

  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 0
        max-wait: -1
    timeout: 5000


mybatis:
  type-aliases-package: cn.edu.xmu.oomall.other.model.po
  mapper-locations: classpath*:cn.edu.xmu.oomall.other.mapper/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql

privilegeservice:
  initialization: false
  lockerExpireTime: 30
  dav:
    username: ooad_javaee
    password: 12345678
    baseUrl: http://172.16.4.1/webdav/test
  user:
    expiretime: 600
  role:
    expiretime: 600
  login:
    multiply: false
    jwtExpire: 3600
  bloomfilter:
    new-user-email:
      error-rate: 0.001
      capacity: 1000
    new-user-mobile:
      error-rate: 0.001
      capacity: 1000
    new-user-name:
      error-rate: 0.001
      capacity: 1000
other:
  bloomfilter:
    new-coupon:
      error-rate: 0.001
      capacity: 1000
