package cn.edu.xmu.oomall.other.mapper;

import cn.edu.xmu.oomall.other.model.po.AddressPo;
import cn.edu.xmu.oomall.other.model.po.AddressPoExample;
import java.util.List;

public interface AddressPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_address
     *
     * @mbg.generated
     */
    int insert(AddressPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_address
     *
     * @mbg.generated
     */
    int insertSelective(AddressPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_address
     *
     * @mbg.generated
     */
    List<AddressPo> selectByExample(AddressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_address
     *
     * @mbg.generated
     */
    AddressPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AddressPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AddressPo record);
}