package cn.edu.xmu.oomall.other.mapper;

import cn.edu.xmu.oomall.other.model.po.RevenueItemPo;
import cn.edu.xmu.oomall.other.model.po.RevenueItemPoExample;
import java.util.List;

public interface RevenueItemPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_revenue_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_revenue_item
     *
     * @mbg.generated
     */
    int insert(RevenueItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_revenue_item
     *
     * @mbg.generated
     */
    int insertSelective(RevenueItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_revenue_item
     *
     * @mbg.generated
     */
    List<RevenueItemPo> selectByExample(RevenueItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_revenue_item
     *
     * @mbg.generated
     */
    RevenueItemPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_revenue_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RevenueItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_revenue_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RevenueItemPo record);
}