package cn.edu.xmu.oomall.other.mapper;

import cn.edu.xmu.oomall.other.model.po.SharePo;
import cn.edu.xmu.oomall.other.model.po.SharePoExample;
import java.util.List;

public interface SharePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share
     *
     * @mbg.generated
     */
    int insert(SharePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share
     *
     * @mbg.generated
     */
    int insertSelective(SharePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share
     *
     * @mbg.generated
     */
    List<SharePo> selectByExample(SharePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share
     *
     * @mbg.generated
     */
    SharePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SharePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_share
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SharePo record);
}