package cn.edu.xmu.oomall.other.model.po;

import java.time.LocalDateTime;

public class LiquidationPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.shop_id
     *
     * @mbg.generated
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.liquid_date
     *
     * @mbg.generated
     */
    private LocalDateTime liquidDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.express_fee
     *
     * @mbg.generated
     */
    private Long expressFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.commission
     *
     * @mbg.generated
     */
    private Long commission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.point
     *
     * @mbg.generated
     */
    private Long point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.shop_revenue
     *
     * @mbg.generated
     */
    private Long shopRevenue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.creator_id
     *
     * @mbg.generated
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.modifier_id
     *
     * @mbg.generated
     */
    private Long modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_liquidation.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.id
     *
     * @return the value of oomall_liquidation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.id
     *
     * @param id the value for oomall_liquidation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.shop_id
     *
     * @return the value of oomall_liquidation.shop_id
     *
     * @mbg.generated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.shop_id
     *
     * @param shopId the value for oomall_liquidation.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.shop_name
     *
     * @return the value of oomall_liquidation.shop_name
     *
     * @mbg.generated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.shop_name
     *
     * @param shopName the value for oomall_liquidation.shop_name
     *
     * @mbg.generated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.liquid_date
     *
     * @return the value of oomall_liquidation.liquid_date
     *
     * @mbg.generated
     */
    public LocalDateTime getLiquidDate() {
        return liquidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.liquid_date
     *
     * @param liquidDate the value for oomall_liquidation.liquid_date
     *
     * @mbg.generated
     */
    public void setLiquidDate(LocalDateTime liquidDate) {
        this.liquidDate = liquidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.express_fee
     *
     * @return the value of oomall_liquidation.express_fee
     *
     * @mbg.generated
     */
    public Long getExpressFee() {
        return expressFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.express_fee
     *
     * @param expressFee the value for oomall_liquidation.express_fee
     *
     * @mbg.generated
     */
    public void setExpressFee(Long expressFee) {
        this.expressFee = expressFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.commission
     *
     * @return the value of oomall_liquidation.commission
     *
     * @mbg.generated
     */
    public Long getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.commission
     *
     * @param commission the value for oomall_liquidation.commission
     *
     * @mbg.generated
     */
    public void setCommission(Long commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.point
     *
     * @return the value of oomall_liquidation.point
     *
     * @mbg.generated
     */
    public Long getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.point
     *
     * @param point the value for oomall_liquidation.point
     *
     * @mbg.generated
     */
    public void setPoint(Long point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.state
     *
     * @return the value of oomall_liquidation.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.state
     *
     * @param state the value for oomall_liquidation.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.shop_revenue
     *
     * @return the value of oomall_liquidation.shop_revenue
     *
     * @mbg.generated
     */
    public Long getShopRevenue() {
        return shopRevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.shop_revenue
     *
     * @param shopRevenue the value for oomall_liquidation.shop_revenue
     *
     * @mbg.generated
     */
    public void setShopRevenue(Long shopRevenue) {
        this.shopRevenue = shopRevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.creator_id
     *
     * @return the value of oomall_liquidation.creator_id
     *
     * @mbg.generated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.creator_id
     *
     * @param creatorId the value for oomall_liquidation.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.creator_name
     *
     * @return the value of oomall_liquidation.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.creator_name
     *
     * @param creatorName the value for oomall_liquidation.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.modifier_id
     *
     * @return the value of oomall_liquidation.modifier_id
     *
     * @mbg.generated
     */
    public Long getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.modifier_id
     *
     * @param modifierId the value for oomall_liquidation.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(Long modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.modifier_name
     *
     * @return the value of oomall_liquidation.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.modifier_name
     *
     * @param modifierName the value for oomall_liquidation.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.gmt_create
     *
     * @return the value of oomall_liquidation.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.gmt_create
     *
     * @param gmtCreate the value for oomall_liquidation.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_liquidation.gmt_modified
     *
     * @return the value of oomall_liquidation.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_liquidation.gmt_modified
     *
     * @param gmtModified the value for oomall_liquidation.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}