package cn.edu.xmu.oomall.other.model.po;

import java.time.LocalDateTime;

public class RevenueItemPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.liquid_id
     *
     * @mbg.generated
     */
    private Long liquidId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.payment_id
     *
     * @mbg.generated
     */
    private Long paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.shop_id
     *
     * @mbg.generated
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.orderitem_id
     *
     * @mbg.generated
     */
    private Long orderitemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.amount
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.express_fee
     *
     * @mbg.generated
     */
    private Long expressFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.commission
     *
     * @mbg.generated
     */
    private Long commission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.point
     *
     * @mbg.generated
     */
    private Long point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.sharer_id
     *
     * @mbg.generated
     */
    private Long sharerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.shop_revenue
     *
     * @mbg.generated
     */
    private Long shopRevenue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.creator_id
     *
     * @mbg.generated
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.modifier_id
     *
     * @mbg.generated
     */
    private Long modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_revenue_item.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.id
     *
     * @return the value of oomall_revenue_item.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.id
     *
     * @param id the value for oomall_revenue_item.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.liquid_id
     *
     * @return the value of oomall_revenue_item.liquid_id
     *
     * @mbg.generated
     */
    public Long getLiquidId() {
        return liquidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.liquid_id
     *
     * @param liquidId the value for oomall_revenue_item.liquid_id
     *
     * @mbg.generated
     */
    public void setLiquidId(Long liquidId) {
        this.liquidId = liquidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.payment_id
     *
     * @return the value of oomall_revenue_item.payment_id
     *
     * @mbg.generated
     */
    public Long getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.payment_id
     *
     * @param paymentId the value for oomall_revenue_item.payment_id
     *
     * @mbg.generated
     */
    public void setPaymentId(Long paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.shop_id
     *
     * @return the value of oomall_revenue_item.shop_id
     *
     * @mbg.generated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.shop_id
     *
     * @param shopId the value for oomall_revenue_item.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.order_id
     *
     * @return the value of oomall_revenue_item.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.order_id
     *
     * @param orderId the value for oomall_revenue_item.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.orderitem_id
     *
     * @return the value of oomall_revenue_item.orderitem_id
     *
     * @mbg.generated
     */
    public Long getOrderitemId() {
        return orderitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.orderitem_id
     *
     * @param orderitemId the value for oomall_revenue_item.orderitem_id
     *
     * @mbg.generated
     */
    public void setOrderitemId(Long orderitemId) {
        this.orderitemId = orderitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.quantity
     *
     * @return the value of oomall_revenue_item.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.quantity
     *
     * @param quantity the value for oomall_revenue_item.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.product_id
     *
     * @return the value of oomall_revenue_item.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.product_id
     *
     * @param productId the value for oomall_revenue_item.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.product_name
     *
     * @return the value of oomall_revenue_item.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.product_name
     *
     * @param productName the value for oomall_revenue_item.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.amount
     *
     * @return the value of oomall_revenue_item.amount
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.amount
     *
     * @param amount the value for oomall_revenue_item.amount
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.express_fee
     *
     * @return the value of oomall_revenue_item.express_fee
     *
     * @mbg.generated
     */
    public Long getExpressFee() {
        return expressFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.express_fee
     *
     * @param expressFee the value for oomall_revenue_item.express_fee
     *
     * @mbg.generated
     */
    public void setExpressFee(Long expressFee) {
        this.expressFee = expressFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.commission
     *
     * @return the value of oomall_revenue_item.commission
     *
     * @mbg.generated
     */
    public Long getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.commission
     *
     * @param commission the value for oomall_revenue_item.commission
     *
     * @mbg.generated
     */
    public void setCommission(Long commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.point
     *
     * @return the value of oomall_revenue_item.point
     *
     * @mbg.generated
     */
    public Long getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.point
     *
     * @param point the value for oomall_revenue_item.point
     *
     * @mbg.generated
     */
    public void setPoint(Long point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.sharer_id
     *
     * @return the value of oomall_revenue_item.sharer_id
     *
     * @mbg.generated
     */
    public Long getSharerId() {
        return sharerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.sharer_id
     *
     * @param sharerId the value for oomall_revenue_item.sharer_id
     *
     * @mbg.generated
     */
    public void setSharerId(Long sharerId) {
        this.sharerId = sharerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.shop_revenue
     *
     * @return the value of oomall_revenue_item.shop_revenue
     *
     * @mbg.generated
     */
    public Long getShopRevenue() {
        return shopRevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.shop_revenue
     *
     * @param shopRevenue the value for oomall_revenue_item.shop_revenue
     *
     * @mbg.generated
     */
    public void setShopRevenue(Long shopRevenue) {
        this.shopRevenue = shopRevenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.creator_id
     *
     * @return the value of oomall_revenue_item.creator_id
     *
     * @mbg.generated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.creator_id
     *
     * @param creatorId the value for oomall_revenue_item.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.creator_name
     *
     * @return the value of oomall_revenue_item.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.creator_name
     *
     * @param creatorName the value for oomall_revenue_item.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.modifier_id
     *
     * @return the value of oomall_revenue_item.modifier_id
     *
     * @mbg.generated
     */
    public Long getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.modifier_id
     *
     * @param modifierId the value for oomall_revenue_item.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(Long modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.modifier_name
     *
     * @return the value of oomall_revenue_item.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.modifier_name
     *
     * @param modifierName the value for oomall_revenue_item.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.gmt_create
     *
     * @return the value of oomall_revenue_item.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.gmt_create
     *
     * @param gmtCreate the value for oomall_revenue_item.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_revenue_item.gmt_modified
     *
     * @return the value of oomall_revenue_item.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_revenue_item.gmt_modified
     *
     * @param gmtModified the value for oomall_revenue_item.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}