package cn.edu.xmu.oomall.other.model.po;

import java.time.LocalDateTime;

public class SharePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_share.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_share.sharer_id
     *
     * @mbg.generated
     */
    private Long sharerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_share.share_act_id
     *
     * @mbg.generated
     */
    private Long shareActId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_share.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_share.onsale_id
     *
     * @mbg.generated
     */
    private Long onsaleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_share.quantity
     *
     * @mbg.generated
     */
    private Long quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_share.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_share.creator_id
     *
     * @mbg.generated
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_share.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_share.modifier_id
     *
     * @mbg.generated
     */
    private Long modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_share.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_share.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oomall_share.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_share.id
     *
     * @return the value of oomall_share.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_share.id
     *
     * @param id the value for oomall_share.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_share.sharer_id
     *
     * @return the value of oomall_share.sharer_id
     *
     * @mbg.generated
     */
    public Long getSharerId() {
        return sharerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_share.sharer_id
     *
     * @param sharerId the value for oomall_share.sharer_id
     *
     * @mbg.generated
     */
    public void setSharerId(Long sharerId) {
        this.sharerId = sharerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_share.share_act_id
     *
     * @return the value of oomall_share.share_act_id
     *
     * @mbg.generated
     */
    public Long getShareActId() {
        return shareActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_share.share_act_id
     *
     * @param shareActId the value for oomall_share.share_act_id
     *
     * @mbg.generated
     */
    public void setShareActId(Long shareActId) {
        this.shareActId = shareActId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_share.product_id
     *
     * @return the value of oomall_share.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_share.product_id
     *
     * @param productId the value for oomall_share.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_share.onsale_id
     *
     * @return the value of oomall_share.onsale_id
     *
     * @mbg.generated
     */
    public Long getOnsaleId() {
        return onsaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_share.onsale_id
     *
     * @param onsaleId the value for oomall_share.onsale_id
     *
     * @mbg.generated
     */
    public void setOnsaleId(Long onsaleId) {
        this.onsaleId = onsaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_share.quantity
     *
     * @return the value of oomall_share.quantity
     *
     * @mbg.generated
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_share.quantity
     *
     * @param quantity the value for oomall_share.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_share.state
     *
     * @return the value of oomall_share.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_share.state
     *
     * @param state the value for oomall_share.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_share.creator_id
     *
     * @return the value of oomall_share.creator_id
     *
     * @mbg.generated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_share.creator_id
     *
     * @param creatorId the value for oomall_share.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_share.creator_name
     *
     * @return the value of oomall_share.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_share.creator_name
     *
     * @param creatorName the value for oomall_share.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_share.modifier_id
     *
     * @return the value of oomall_share.modifier_id
     *
     * @mbg.generated
     */
    public Long getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_share.modifier_id
     *
     * @param modifierId the value for oomall_share.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(Long modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_share.modifier_name
     *
     * @return the value of oomall_share.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_share.modifier_name
     *
     * @param modifierName the value for oomall_share.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_share.gmt_create
     *
     * @return the value of oomall_share.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_share.gmt_create
     *
     * @param gmtCreate the value for oomall_share.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oomall_share.gmt_modified
     *
     * @return the value of oomall_share.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oomall_share.gmt_modified
     *
     * @param gmtModified the value for oomall_share.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}